### ISSUE TITLE
add benchmark scripts

### ISSUE THREAD

**Issue by antgonza** [biocore/mds-approximations#4]
scripts that run the benchmarks

**Comment by HannesHolste** [comment]
I setup my barnacle environment and wrote a test job submission. Now ready to scope out our actual benchmarking.

**Goal:** 
Graph the performance of each PCoA algorithm, and visualize the resulting eigenvectors/vals using Emperor, as the input size grows larger.

**Definition of "performance":**
- Memory usage
- Time to completion
- what else?

**Questions:**
1. What step to grow input size (distance matrix) at? With each benchmark, increase `N * N` to `(N+1000)*(N+1000)` ?
2. Run all experiments 3x, then take the average performance indicators per set of 3 runs. 
3. Use [skbio.core.distance.randdm](http://scikit-bio.org/docs/0.1.4/generated/skbio.core.distance.randdm.html) to generate random distance matrix of varying size?
4. Compute performance data on one real, large EMP distance matrix? If so, where to get this data from?
5. Just to confirm: we also want to visualize the resulting eigenvecs/vals using emperor, right, to see how much the visual differs from skbio's current ordination methods?
6. How to measure time to completion? I assume multiple jobs run on the same hardware on barnacle... how to ensure we get an accurate measure of CPU time just for our process?
I'd appreciate your thoughts @antgonza @ElDeveloper.

**Comment by antgonza** [comment]
I think most of your questions are answered in [this document](https://docs.google.com/document/d/1PtKDKfYWS4KZBJ_1udu5efGDx5yzI311_rjVPq4Fyi0/edit#heading=h.e71et2642rya), could you confirm? BTW I think using the command `time` should suffice. 

Random tables: In previous tests we used random contingency tables and then calculated the Euclidean distance matrix, which generated crazy sized distances and became a bottleneck for actual testing. Thus, point 3 makes a lot of sense.

Real tables: Perhaps this is the easiest to start with as we already have the final table, see document. 

Anyway, let us know when these are ready so we can coordinate offline to reserve a specific node in barnacle and start the tests.

**Comment by ElDeveloper** [comment]
I agree with @antgonza, but would like to add the following to these points:

> 1. What step to grow input size (distance matrix) at? With each benchmark, increase NN to (N+1000)(N+1000) ?

This sounds fine.

> 1. Run all experiments 3x, then take the average performance indicators per set of 3 runs.

I would probably do 10 times.

> 1. Use skbio.core.distance.randdm to generate random distance matrix of varying size?

👍 

> 1. Compute performance data on one real, large EMP distance matrix? If so, where to get this data from?

We just begun generating distance matrices for the Full EMP dataset, I believe UniFrac (unweighted and weighted were just recently generated), though I also have the matrices for Jaccard and Bray-Curtis.

> 1. Just to confirm: we also want to visualize the resulting eigenvecs/vals using emperor, right, to see how much the visual differs from skbio's current ordination methods?

For some cases, yes. I would leave this as a secondary step, we can always do this once the above steps are completed.

> 1. How to measure time to completion? I assume multiple jobs run on the same hardware on barnacle... how to ensure we get an accurate measure of CPU time just for our process?

I agree with @antgonza, but I think @josenavas has measured more running times than me, so whatever he suggests.

**Comment by antgonza** [comment]
Note that procrustes vs. kruskal stress should give us some guidance about which ones to visually inspect.

**Comment by josenavas** [comment]
> I would probably do 10 times.

I would run it 3 times and if the std dev is big, then 10 times - I think this is what I've seen around.

> How to measure time to completion? I assume multiple jobs run on the same hardware on barnacle... how to ensure we get an accurate measure of CPU time just for our process?

Walltime + node exclusive jobs

**Comment by mortonjt** [comment]
👍 on testing this out on the entire EMP dataset.

In the event that these benchmarks crash and burn on this dataset, I think it is worthwhile investigating distributive options, such as [spark](http://spark.apache.org/docs/latest/mllib-dimensionality-reduction.html).

**Comment by antgonza** [comment]
@HannesHolste, if you still have questions please send an email to organize a meeting so we avoid lots of messages. Thanks!

**Comment by wasade** [comment]
DMs for EMP for weighted/unweighted unifrac are on barnacle. If submitted as a job, than `tracejob` output will track walltime/cputime/peak memory for free, otherwise `/usr/bin/time` works but recommend mucking with the flags to get the output you want. Also, it is important to note that `/usr/bin/time` on OSX is not the same as `/usr/bin/time` on Linux. 

It is important to characterize cpu time as well as walltime in case some methods are implicitly threaded (which we just discovered with QIIME's `principal_coordinates.py`)

For matrix growth, I've been a fan of powers of 2 or 10. 10 is a pain here as the growth is too fast, but powers of 2 (from, say 2**5 -> 2**14) would work for EMP

**Comment by josenavas** [comment]
Agree with @wasade regarding powers of 2 (or 10) as this will show a better estimate of the scalability. For the usage of time, you can check [this wrapper](https://github.com/qiime/QIIME-Scaling/blob/master/scripts/timing_wrapper.sh) for linux's /usr/bin/time that I wrote a while ago, and [here](https://github.com/qiime/QIIME-Scaling/blob/master/scaling/interfaces/optparse/input_handler.py#L143) is the code that I used to parse the format of that wrapper.
