### ISSUE TITLE
Python=3?

### ISSUE THREAD

**Issue by mortonjt** [biocore/mds-approximations#8]
I've been compiling `scmds` and `nystrom` from pycogent.

Now, pycogent is built on python2.  In our first meeting, we decided that we wanted to make this Python3 compatible.

However, this means that we need to make all of the functions ported from pycogent python3 compatible.
Do we really care if this package is python3 compatible?  This is just a benchmarking suite.  I'm not sure if it is time well spent if we make everything python3 compatible.  Any thoughts @ElDeveloper @antgonza @josenavas ?

**Comment by antgonza** [comment]
IMOO: we don't care.

**Comment by ElDeveloper** [comment]
:+1: @antgonza.

**Comment by josenavas** [comment]
The only advantage that I can see of having it already in Py3 is that if we want to later add some of these methods back to skbio they'll be already in Py3 - so we are agreeing on delaying this burden given that the number of methods that we are going to transfer to skbio is less than the ones that we are benchmarking.

Is this correct?

**Comment by antgonza** [comment]
Yes, we should only fully transfer those that are possible good solutions. All the rest will still live here.

**Comment by ElDeveloper** [comment]
Hmmm, that's true, though getting all methods to be py2/3 compatible
might be more time-consuming at first than make sure 1 of them is
compatible. Theory says that's the case, but not sure what will happen
in practice.

**Comment by mortonjt** [comment]
Ok.  Let's shoot for python2 only then.

I seriously doubt most of these methods will be ported to skbio.

**Comment by ElDeveloper** [comment]
Sounds good!

**Comment by ElDeveloper** [comment]
Closing this, as we've all agreed on a resolution.
